repos:
  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: pytest --strict-markers -x
        language: system
        pass_filenames: false
      - id: lint
        name: lint
        entry: ruff check .
        language: system
        pass_filenames: false
      - id: typecheck
        name: typecheck
        entry: mypy .
        language: system
        pass_filenames: false
